### ISSUE TITLE
Comentarios de Dante - (cillo)

### ISSUE THREAD

**Issue by snozz1001** [snozzono/Enfermeria-a-domicilio#1]
- Cambié la visual de la VentanaPrincipal

- Añadí una VentanaAdminstradorPrincipal:
--- La idea es tener todas las acciones del admin en un solo lugar
--- Mostrar datos: lleva a una vista que permite elegir entre Tecnico y Paciente, y da la opción de filtrar por algún criterio X (req. de la evaluación)
--- Ingresar datos: lo mismo, pero c/ med también. Esto aún no lo tengo claro en código, así que no estoy seguro si sería bueno tener la opción o restringirlo a Tecnico/Pac.
--- Eliminar datos: lo mismo
--- Ver resumen: te muestra toda la info de una O podría mostrar algún tipo de estadística (req. para la evaluación)

- La idea sería hacer algo similar para el Tecnico, con menos opciones

- Añadí los métodos buscar/eliminar/obtenerTodos en los DAO que no los tenían
--- En ProcedimientoDAO no completé el obtenerTodos porque no estoy seguro de cómo hacerlo cuando hay 2 constructores

- Necesito saber qué métodos custom tienes en mente para incorporarlos o avanzarlos en mi tiempo

- También si tienes ideas sobre la clase colaborativa que se menciona en el doc de Trabajo Final

**Comment by snozzono** [comment]
> Cambié la visual de la VentanaPrincipal

No es prioridad pero bueno

> Añadí una VentanaAdminstradorPrincipal, La idea es tener todas las acciones del admin en un solo lugar, aquí explico que hace cada botón:
> -  Mostrar datos: lleva a una vista que permite elegir entre Tecnico y Paciente, y da la opción de filtrar por algún criterio X (req. de la evaluación)
> - Ingresar datos: lo mismo, pero c/ med también. Esto aún no lo tengo claro en código, así que no estoy seguro si sería bueno tener la opción o restringirlo a Tecnico/Pac.
> - Eliminar datos: lo mismo
> - Ver resumen: te muestra toda la info de una O podría mostrar algún tipo de estadística (req. para la evaluación)

Terminemos lo que tenemos pendiente

> La idea sería hacer algo similar para el Tecnico, con menos opciones

Lo mismo de arriba

  > Añadí los métodos buscar/eliminar/obtenerTodos en los DAO que no los tenían

Cool, los metodos que hiciste me ayudaron mucho a terminar rapido los formularios. Aunque cuidado con escribir codigo que no vayamos a usar. Personalmente preferiria que vayas viendo primero en las vistas que es lo necesario y que no
    
> En ProcedimientoDAO no completé el obtenerTodos porque no estoy seguro de cómo hacerlo cuando hay 2 constructores

Segun yo no deberia problema con que hayan x cantidad de constructores, deberia tirar null a menos que no lo haya puesto asi en la bd.

> Necesito saber qué métodos custom tienes en mente para incorporarlos o avanzarlos en mi tiempo

Entre VentanaPaciente o VentanaMain deberia haber un botón que desglose la cuenta, no sé por qué no está ahí. Mas no se me ocurre, como dije, Hay que terminar lo que tenemos y luego ir agregando sobre la marcha. No se me ocurre ninguna función que necesite nuevos metodos. Aunque en general cualquier cosa que involucre aritmetica sirve. 

> También si tienes ideas sobre la clase colaborativa que se menciona en el doc de Trabajo Final

Podriamos meter medicamentos y procedimientos en paciente y ya
https://www.tutorialesprogramacionya.com/javaya/detalleconcepto.php?codigo=101&punto=&inicio=20
